komeilmehranfar/visa-sponsers-companies-for-iranians

- README.md
Hey @komeilmehranfar, there is a German company called [Check24](https://www.linkedin.com/company/check24-vergleichsportal-gmbh/) that supports with relocation and sponsors work permit (blue card).
Hope someone can find a suitable position, I had interviews but got rejected.
> docs: german company check24

- README.md
Hey @komeilmehranfar , Sporradar is located in Bermen, Germany. They also support with work permit (blue card). 
I have a friend whom was relocated by them.
> docs: german company sportradar

- README.md
Hey @komeilmehranfar, I know sb who has been relocated to Berlin by Hello Fresh.
> docs: german company hellofresh

- README.md
3 more companies have been added to README.md
> Add more companies

- README.md
Hey @komeilmehranfar , I have a friend at Taxdoo, they support with relocation to Germany with blue card.
> docs: german company taxdoo

- README.md
Hey @komeilmehranfar, Alasco will support with relocation, I know two Iranian people working for them.
> docs: german company Alasco

- README.md
hey @komeilmehranfar , one of my friends work at DataGuard, they support with relocation to Munich and of course blue card.
> docs: german company dataguard

- README.md
Hey @komeilmehranfar , I had interview with Vimcar, they have offices in Berlin and Switzerland and support relocation to Germany with blue card.
> docs: vimcar german company

- README.md
Hey @komeilmehranfar , I had interviews and received code-challenge with Sensory minds, they support with relocation to Frankfurt region, Germany. However, they're a bit weird.
> docs: german web agency sensory-minds

- README.md
Hey there, 
I'm Nicolas, and I work at [DataChef](https://alpha.datachef.co/). Our founder, [Ashkan](https://www.linkedin.com/in/ashkanroshanayi/), is Iranian and we are actively hiring Iranians. We hire people in Iran, and we also help them relocate to the Netherlands - it's up to each individual as we are a remote company. We sponsor work permits here, of course. 
I hope you'll be able to include us in your list. I added that we are actively hiring Iranians, as I thought that it made sense to mention it. 
Cheers from Amsterdam!
Nicolas
> Introducing DataChef

- README.md
Hey @komeilmehranfar , I know a frontend-developer which was relocated to their office in Barcelona, Spain. They can relocate to both Netherlands and Spain.
> docs: holland company mollie

- README.md
Hey @komeilmehranfar , I had interviews with Energy Robotics, they support with visa (work permit) but don't have relocation package, each person should cover his/her expenses to move.
> docs: german startup energy-robotics

- README.md
Hey @komeilmehranfar , One of my friends work there, the CEO is Irani and they support with the visa sponsorship and relocation package. Their stack is C# with WPF, they relocate juniors as well.
> docs: holland company nearfield

- README.md
Hey @komeilmehranfar , One of my close friends was relocated by them, such a generous relocation package! 
They support Junior relocation and work permit as well.
> docs: holland company nn-group

- README.md
Hey @komeilmehranfar , 
I know two people which were relocated to Amsterdam by them, One Product owner and the other one frontend developer. The CEO is half Irani and half Swedish.
> docs: holland company bunq

- README.md
I know at least three Iranians hired by _Jaja Finance_. But I am not sure if it support relocation.
> Add Jaja Finance

- README.md
Added companies in Germany that give interview and have visa sponsorship to Iranian people which I have already interviewed with them
> Add companies in Germany

- README.md
> Add few companies

- README.md
- AG5 Skills Management Software [Website](https://www.ag5.com) - [Linkedin](https://www.linkedin.com/company/ag5skillsintelligencesoftware)
- dé VakantieDiscounter [Website](https://werkenbij.vakantiediscounter.nl) - [Linkedin](https://www.linkedin.com/company/vakantiediscounter)
- Babbel [Website](https://www.babbel.com) - [Linkedin](https://www.linkedin.com/company/babbel-com)
> Add Ag5,Vakantie to NL, Add Babbel to Gr

- README.md
Hi,
I added the `eurowings digital` company.
Please review and merge it.
Mohammad
> feat: add eurowings digital company

- README.md
I recently went through a job search process that involved seeking positions offering visa sponsorship in the UK. As I identified companies offering sponsorship through this process, I added some of them to the England list, inlcuding the company I'm currently working at. I’m not sure whether the last two companies provide relocation packages, but they do offer visa sponsorship.
The website link I added to verify if a company offers sponsorship in the UK helped me a lot, hopefully it will come handy for anyone looking for a job in the UK as well. Cheers.
> Add some companies to England list
